### ISSUE TITLE
Accessing source code.

### ISSUE THREAD

**Issue by Grossdm** [porkopek/Focuser#1]
Hello @porkopek, I just installed your [Focuser addon in Firefox](https://addons.mozilla.org/firefox/addon/focuser) and look forward to using it.

My question is about your [GooFast! addon](https://addons.mozilla.org/firefox/addon/goofast).  It is released under MIT/X11 License, but I can't find the source code for it.

Please help me to resolve this fairly minor problem.

Thanks,
Doug®

**Comment by porkopek** [comment]
Hi, Grossdm,
It is not released, because I did not think it would be usefull, but I will publish the code here the next week.
Glad if Focuser is useful to you

**Comment by Grossdm** [comment]
Thank you!
Being able to access source code helps me (_not_ a dev) to understand and learn.

**Comment by porkopek** [comment]
Sorry, I unpublished GooFast because was not mature enough. But I published another extension, Linguee+, that is open sourced in my profile. It's not very clean. I'm not a developer, just a translator

**Comment by Grossdm** [comment]
Great, thanks!
